import React, { useMemo, useState } from "react";
import { T } from "../theme.js";
import { PageShell } from "../components/PageShell.jsx";

const TERMS = [
  { t: "SPF (Sender Policy Framework)", g: "Authentication", d: "A DNS record listing which mail servers are allowed to send email for a domain. The receiving server checks whether the connecting IP is on that list. A pass means the sending IP was authorized; a fail means it was not — a strong spoofing signal." },
  { t: "DKIM (DomainKeys Identified Mail)", g: "Authentication", d: "A cryptographic signature added to outgoing mail using a private key; the receiver verifies it with a public key published in DNS. A valid signature proves the message wasn't altered in transit and was signed by the claimed domain." },
  { t: "DMARC (Domain-based Message Authentication, Reporting & Conformance)", g: "Authentication", d: "A policy layer on top of SPF and DKIM. It requires that at least one of them not only pass but also be \"aligned\" with the visible From: domain, and tells receivers what to do with mail that fails (none/quarantine/reject)." },
  { t: "ARC (Authenticated Received Chain)", g: "Authentication", d: "Preserves the original authentication results as a message passes through intermediaries (like mailing lists) that might otherwise break SPF/DKIM/DMARC, letting the final receiver see what earlier hops verified." },
  { t: "Alignment", g: "Authentication", d: "Whether the domain that passed SPF or DKIM matches (at the organizational level) the domain shown in the visible From: header. Passing SPF for an unrelated domain while displaying a trusted brand name is a classic bypass DMARC alignment is designed to catch." },
  { t: "Return-Path", g: "Headers", d: "The address bounces (delivery failure notices) are sent to. Often differs from the visible From: address for legitimate mailing lists and ESPs — but combined with other red flags it can indicate spoofing." },
  { t: "Envelope From (MAIL FROM)", g: "Headers", d: "The sender address used during the actual SMTP transaction, which SPF checks against. It's often invisible in your mail client and can differ from the From: header you actually see." },
  { t: "From Header", g: "Headers", d: "The visible \"From:\" address and display name shown to the recipient. Attackers control this freely, which is exactly why it can't be trusted on its own — it must be checked against SPF/DKIM/DMARC results." },
  { t: "Reply-To", g: "Headers", d: "An optional header that redirects where replies go, independent of the From: address. A Reply-To pointing to a freemail address while From: shows a corporate brand is a common business-email-compromise (BEC) pattern." },
  { t: "Message-ID", g: "Headers", d: "A unique identifier generated by the sending system for each message. Almost all legitimate mail transfer agents add one automatically; its absence, or a domain mismatch, is a mild anomaly signal." },
  { t: "Received Headers", g: "Routing", d: "Stamped by every mail server the message passes through, each recording the hop before it, a timestamp, and often the connecting IP. Read bottom-to-top, they reconstruct the message's journey from origin to your inbox." },
  { t: "SMTP (Simple Mail Transfer Protocol)", g: "Routing", d: "The standard protocol mail servers use to relay email to one another. Understanding SMTP conversation basics (HELO, MAIL FROM, RCPT TO) helps make sense of Received headers." },
  { t: "HELO / EHLO", g: "Routing", d: "The hostname a connecting server announces at the start of an SMTP conversation. Comparing this claimed name against the connection's actual reverse-DNS name can reveal a misconfigured or identity-masking sender." },
  { t: "MX Record", g: "DNS", d: "A DNS record telling the internet which mail servers are responsible for receiving email for a domain. A domain with no MX record cannot receive mail — a hallmark of throwaway phishing infrastructure that only sends." },
  { t: "RDAP (Registration Data Access Protocol)", g: "DNS", d: "The modern, structured, JSON-over-HTTPS successor to WHOIS. Used here to look up when a domain was registered — a domain created days before sending \"urgent\" mail is one of the strongest phishing signals available. Not every registry has adopted RDAP yet, so coverage varies by TLD." },
  { t: "Domain age", g: "DNS", d: "How long ago a domain was registered, taken from RDAP registration data. Brand-new domains are disproportionately used in disposable phishing infrastructure, while long-established domains are less commonly burned this way — though not impossible, since legitimate accounts can be compromised too." },
  { t: "Reverse DNS (rDNS / PTR)", g: "DNS", d: "A DNS lookup that maps an IP address back to a hostname (the reverse of a normal A-record lookup). Legitimate mail servers almost always have a PTR record; its absence is a mild anomaly." },
  { t: "FCrDNS (Forward-Confirmed reverse DNS)", g: "DNS", d: "A stronger check than plain rDNS: look up the PTR name for an IP, then look up that name's own A record, and confirm it points back to the original IP. When both directions agree, the identity is much harder to fake." },
  { t: "ASN (Autonomous System Number)", g: "DNS", d: "An identifier for the network/organization that owns a block of IP addresses. Useful for spotting whether a sending IP belongs to a known mail provider, a generic hosting/VPS company, or a residential ISP." },
  { t: "MIME (Multipurpose Internet Mail Extensions)", g: "Format", d: "The standard that lets email messages carry more than plain text — HTML, attachments, and multiple parts. The blank line separating headers from the MIME body is exactly where this tool stops reading." },
  { t: "Phishing", g: "Threats", d: "Fraudulent email designed to trick the recipient into revealing credentials, transferring funds, or installing malware, typically by impersonating a trusted sender or brand." },
  { t: "Spoofing", g: "Threats", d: "Forging the sender information of an email — most often the From: address — to make it appear as though it came from someone other than the actual sender." },
  { t: "Display Name Impersonation", g: "Threats", d: "A spoofing technique that abuses the visible display name (e.g. \"Microsoft 365 Admin\") while the underlying email address is unrelated and often a free webmail account — deceptive to a quick glance even when authentication technically fails." },
  { t: "Homograph / Homoglyph Domain", g: "Threats", d: "A look-alike domain using visually similar characters (including internationalized/punycode characters) to impersonate a legitimate brand's domain, e.g. substituting a Cyrillic \"а\" for a Latin \"a\"." },
  { t: "Business Email Compromise (BEC)", g: "Threats", d: "A targeted fraud scheme, often using a spoofed or compromised executive/vendor account, to convince an employee to wire funds or divulge sensitive data — frequently combined with Reply-To redirection and urgency language." },
  { t: "Secure Email Gateway (SEG)", g: "Infrastructure", d: "An inline filtering service (e.g. Proofpoint, Mimecast, Barracuda, Cisco IronPort) that inspects and relays mail before it reaches the final mail server. Its hop in the Received chain is expected filtering infrastructure, not suspicious forwarding." },
  { t: "ESP (Email Service Provider)", g: "Infrastructure", d: "A third-party platform (SendGrid, Mailchimp, Amazon SES, Mailgun, and others) that sends transactional or marketing email on a domain's behalf. ESPs often use their own infrastructure for the envelope sender, which is why SPF/DKIM alignment interpretation must be ESP-aware rather than treating every mismatch as a red flag." },
  { t: "Open Relay", g: "Infrastructure", d: "A misconfigured mail server that will relay mail from anyone to anyone, historically abused heavily by spammers. Modern legitimate infrastructure almost never operates this way." },
  { t: "Compauth (Composite Authentication)", g: "Infrastructure", d: "Microsoft 365 / Exchange Online's own combined authentication verdict, recorded in Authentication-Results as compauth=pass/fail with a numeric reason code, summarizing its internal SPF/DKIM/DMARC-plus-heuristics decision." },
  { t: "TLS (Transport Layer Security) in SMTP", g: "Infrastructure", d: "Encryption applied to the connection between two mail servers during a hop (often shown as ESMTPS or STARTTLS in Received headers). It protects the message in transit between those two hops but says nothing about sender authenticity." },
];

const GROUP_ORDER = ["Authentication", "Headers", "Routing", "DNS", "Format", "Threats", "Infrastructure"];
const GROUP_COLOR = { Authentication: T.accent, Headers: T.info, Routing: T.good, DNS: "#8FE1B8", Format: T.dim, Threats: T.bad, Infrastructure: T.accent2 };

export function GlossaryPage() {
  const [q, setQ] = useState("");
  const filtered = useMemo(() => {
    const s = q.trim().toLowerCase();
    if (!s) return TERMS;
    return TERMS.filter((x) => x.t.toLowerCase().includes(s) || x.d.toLowerCase().includes(s));
  }, [q]);

  const grouped = useMemo(() => {
    const m = new Map();
    for (const term of filtered) {
      if (!m.has(term.g)) m.set(term.g, []);
      m.get(term.g).push(term);
    }
    return m;
  }, [filtered]);

  return (
    <PageShell
      eyebrow="REFERENCE"
      title="Email security glossary"
      subtitle="Plain-language definitions for every technical term used throughout the analyzer — no prior email-authentication background required."
      wide
    >
      <div style={{ marginBottom: 26 }}>
        <input
          value={q}
          onChange={(e) => setQ(e.target.value)}
          placeholder="Search terms — try “alignment” or “rDNS”…"
          style={{
            width: "100%",
            maxWidth: 420,
            background: T.panel2,
            border: `1px solid ${T.line}`,
            borderRadius: T.r2,
            color: T.ink,
            padding: "11px 16px",
            fontSize: 14,
            fontFamily: T.body,
          }}
        />
        <span style={{ marginLeft: 12, fontSize: 12.5, color: T.faint, fontFamily: T.mono }}>
          {filtered.length} of {TERMS.length} terms
        </span>
      </div>

      {GROUP_ORDER.filter((g) => grouped.has(g)).map((g) => (
        <div key={g} style={{ marginBottom: 26 }}>
          <div
            style={{
              display: "inline-block",
              fontFamily: T.mono,
              fontSize: 11.5,
              fontWeight: 700,
              letterSpacing: 0.8,
              color: GROUP_COLOR[g],
              border: `1px solid ${GROUP_COLOR[g]}44`,
              background: GROUP_COLOR[g] + "14",
              borderRadius: 999,
              padding: "4px 12px",
              marginBottom: 12,
            }}
          >
            {g.toUpperCase()}
          </div>
          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(340px, 1fr))", gap: 12 }}>
            {grouped.get(g).map((term) => (
              <div
                key={term.t}
                style={{
                  background: T.panel,
                  border: `1px solid ${T.line}`,
                  borderRadius: T.r2,
                  padding: "16px 18px",
                  boxShadow: T.shadowSm,
                }}
              >
                <div style={{ fontWeight: 700, color: T.ink, fontSize: 14.5, marginBottom: 6 }}>{term.t}</div>
                <div style={{ fontSize: 13, color: T.dim, lineHeight: 1.6 }}>{term.d}</div>
              </div>
            ))}
          </div>
        </div>
      ))}

      {filtered.length === 0 && (
        <div style={{ color: T.faint, fontSize: 14, padding: "30px 0", textAlign: "center" }}>
          No terms match “{q}”.
        </div>
      )}
    </PageShell>
  );
}
